# Generated by Django 4.0.4 on 2022-06-07 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('period', models.CharField(max_length=100, verbose_name='Period')),
                ('economic_valuation', models.PositiveIntegerField(verbose_name='Economic Valuation')),
                ('creation_date', models.DateField(verbose_name='Creation Date')),
                ('entry_date', models.DateField(verbose_name='Entry date')),
                ('image', models.ImageField(upload_to='media', verbose_name='Image')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratingMuseum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='museum_app.artwork', verbose_name='Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Exibition',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.state')),
                ('state_name', models.CharField(choices=[('Exhibition', 'Exhibition')], max_length=20, verbose_name='State')),
            ],
            bases=('museum_app.state',),
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.artwork')),
                ('technique', models.CharField(max_length=100, verbose_name='Technique')),
                ('style', models.CharField(max_length=100, verbose_name='Style')),
            ],
            bases=('museum_app.artwork',),
        ),
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.state')),
                ('state_name', models.CharField(choices=[('Restoration', 'Restoration')], max_length=20, verbose_name='State')),
                ('restoration_type', models.CharField(max_length=100, verbose_name='Restoration Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('finish_date', models.DateField(verbose_name='Finish Date')),
            ],
            bases=('museum_app.state',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.artwork')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('style', models.CharField(max_length=100, verbose_name='Style')),
            ],
            bases=('museum_app.artwork',),
        ),
        migrations.CreateModel(
            name='Given',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.state')),
                ('state_name', models.CharField(choices=[('Given', 'Given')], max_length=20, verbose_name='State')),
                ('given_time', models.DurationField(verbose_name='Given time')),
                ('amount_received', models.IntegerField(verbose_name='Amount Received')),
                ('collaborating_museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_app.collaboratingmuseum')),
            ],
            bases=('museum_app.state',),
        ),
    ]
