# Generated by Django 4.0.4 on 2022-06-26 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('period', models.CharField(max_length=100, verbose_name='Period')),
                ('economic_valuation', models.PositiveIntegerField(verbose_name='Economic Valuation')),
                ('creation_date', models.DateField(verbose_name='Creation Date')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Entry date')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollaboratingMuseum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Collaborating Museum',
                'verbose_name_plural': 'Collaborating Museums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='State Date and Time')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='museum_app.artwork', verbose_name='Artwork')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.state')),
            ],
            options={
                'verbose_name': 'Exhibition',
                'verbose_name_plural': 'Exhibitions',
                'ordering': ['-date_time'],
                'get_latest_by': 'date_time',
            },
            bases=('museum_app.state',),
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.artwork')),
                ('technique', models.CharField(max_length=100, verbose_name='Technique')),
                ('style', models.CharField(max_length=100, verbose_name='Style')),
            ],
            options={
                'verbose_name': 'Painting',
                'verbose_name_plural': 'Paintings',
                'ordering': ['name'],
            },
            bases=('museum_app.artwork',),
        ),
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.state')),
                ('restoration_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Restoration Type')),
                ('finish_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Finish Date')),
            ],
            options={
                'verbose_name': 'Restoration',
                'verbose_name_plural': 'Restorations',
                'ordering': ['-date_time'],
                'get_latest_by': 'date_time',
            },
            bases=('museum_app.state',),
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('artwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.artwork')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('style', models.CharField(max_length=100, verbose_name='Style')),
            ],
            options={
                'verbose_name': 'Sculpture',
                'verbose_name_plural': 'Sculptures',
                'ordering': ['name'],
            },
            bases=('museum_app.artwork',),
        ),
        migrations.AddField(
            model_name='artwork',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to='museum_app.room', verbose_name='Room'),
        ),
        migrations.CreateModel(
            name='ManagerArtworks',
            fields=[
            ],
            options={
                'verbose_name': 'Economic Value of Artwork',
                'verbose_name_plural': 'Economic Value of Artworks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('museum_app.artwork',),
        ),
        migrations.CreateModel(
            name='ToRestoration',
            fields=[
            ],
            options={
                'verbose_name': 'Artwork to Restoration',
                'verbose_name_plural': 'Artworks to Restoration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('museum_app.artwork',),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('state_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='museum_app.state')),
                ('loan_time', models.PositiveIntegerField(help_text='Loan duration in days', verbose_name='Loan Time')),
                ('amount_received', models.PositiveIntegerField(verbose_name='Amount Received')),
                ('loan_init', models.DateField(blank=True, editable=False, null=True, verbose_name='Loan Start Date')),
                ('collaborating_museum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Collaborating_museum', to='museum_app.collaboratingmuseum')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-date_time'],
                'get_latest_by': 'date_time',
            },
            bases=('museum_app.state',),
        ),
        migrations.CreateModel(
            name='CurrentRestoration',
            fields=[
            ],
            options={
                'verbose_name': 'Artwork Currently Under Restoration',
                'verbose_name_plural': 'Artworks Currently Under Restoration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('museum_app.restoration',),
        ),
        migrations.CreateModel(
            name='LoanWaitList',
            fields=[
            ],
            options={
                'verbose_name': 'Loan Wait List',
                'verbose_name_plural': 'Loan Wait List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('museum_app.loan',),
        ),
    ]
