# Generated by Django 4.0.4 on 2022-06-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='creation_date',
            field=models.PositiveIntegerField(help_text='creation year', verbose_name='Creation Date'),
        ),
    ]
