# Generated by Django 4.0.4 on 2022-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
