# Generated by Django 4.0.4 on 2022-06-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_app', '0002_alter_artwork_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='technique',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technique'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Style'),
        ),
    ]
